class AppStrings {
  static String of(String key, String lang) {
    return _strings[lang]?[key] ?? _strings['km']?[key] ?? key;
  }

  static String get(String key, String lang) => of(key, lang);

  static const Map<String, Map<String, String>> _strings = {
    'km': {
      'home': 'ទំព័រដើម',
      'statistics': 'ស្ថិតិ',
      'savings': 'សន្សំប្រាក់',
      'settings': 'ការកំណត់',
      'all_wallets': 'កាបូបទាំងអស់',
      'total_balance': 'សមតុល្យសរុប',
      'income': 'ចំណូល',
      'expense': 'ចំណាយ',
      'transfer': 'ផ្ទេរប្រាក់',
      'this_month': 'ខែនេះ',
      'today': 'ថ្ងៃនេះ',
      '7_days': '៧ថ្ងៃ',
      'all': 'ទាំងអស់',
      'custom_range': 'ចន្លោះកាលបរិច្ឆេទ',
      'new_tx': 'ប្រតិបត្តិការថ្មី',
      'edit_tx': 'កែប្រតិបត្តិការ',
      'amount': 'ចំនួនទឹកប្រាក់',
      'category': 'ប្រភេទ',
      'wallet': 'កាបូបលុយ',
      'from_wallet': 'ពីកាបូប',
      'to_wallet': 'ទៅកាន់កាបូប',
      'note': 'កំណត់ចំណាំ',
      'date': 'កាលបរិច្ឆេទ',
      'save': 'រក្សាទុក',
      'cancel': 'បោះបង់',
      'delete': 'លុប',
      'savings_goals': 'គោលដៅសន្សំប្រាក់',
      'add_goal': 'បន្ថែមគោលដៅថ្មី',
      'goal_title': 'ឈ្មោះគោលដៅ (ឧ. ទិញម៉ូតូ, សង្គ្រោះបន្ទាន់)',
      'target_amount': 'ចំនួនទឹកប្រាក់គោលដៅ (\$)',
      'current_saved': 'ចំនួនសន្សំបានបច្ចុប្បន្ន (\$)',
      'deposit': 'ដាក់ប្រាក់សន្សំ',
      'withdraw': 'ដកប្រាក់សន្សំ',
      'completed': 'សម្រេចបានជោគជ័យ!',
      'language': 'ភាសា (Language)',
      'backup_restore': 'ទិន្នន័យ និងការបម្រុងទុក',
      'backup_drive': 'បម្រុងទុកទិន្នន័យ (Cloud / Drive Backup)',
      'restore_data': 'ស្តារទិន្នន័យឡើងវិញ (Restore Data)',
      'export_report': 'នាំចេញរបាយការណ៍ (Export PDF / Excel / CSV)',
      'app_lock': 'ចាក់សោកម្មវិធី (App Lock)',
      'dark_mode': 'របៀបងងឹត (Dark Mode)',
      'monthly_budget': 'ថវិកាប្រចាំខែសរុប',
      'exchange_rate': 'អត្រាប្តូរប្រាក់',
      'all_categories': 'ប្រភេទទាំងអស់',
      'stat_overview': 'ស្ថិតិចំណូល-ចំណាយ',
      'month_expense': 'ចំណាយខែនេះ',
      'month_income': 'ចំណូលខែនេះ',
      'recent_7_days': 'ចំណាយ ៧ ថ្ងៃចុងក្រោយ',
      'by_category': 'ចំណាយតាមប្រភេទ',
      'debt_tracker': 'តាមដានបំណុល',
      'debts_and_loans': 'តាមដានបំណុល និងលុយខ្ចី',
      'to_receive': 'គេជំពាក់យើង',
      'to_pay': 'យើងជំពាក់គេ',
      'monthly_trend': 'និន្នាការចំណាយប្រចាំខែ',
      'vs_last_month': 'ធៀបនឹងខែមុន',
      'repay': 'កត់ត្រាការសង',
      'settled': 'សងរួច',
      'smart_insights': 'ការវិភាគឆ្លាតវៃ',
      'daily_avg': 'មធ្យមភាគប្រចាំថ្ងៃ',
      'peak_day': 'ថ្ងៃចំណាយច្រើន',
      'top_category': 'ប្រភេទចំណាយកំពូល',
      'financial_tips': 'គន្លឹះហិរញ្ញវត្ថុ',
      'calendar_view': 'ប្រតិទិន',
      'analytics_view': 'ស្ថិតិ & ក្រាហ្វ',
      'day_transactions': 'ប្រតិបត្តិការប្រចាំថ្ងៃ',
      'no_tx_day': 'គ្មានប្រតិបត្តិការក្នុងថ្ងៃនេះទេ',
    },
    'en': {
      'home': 'Home',
      'statistics': 'Statistics',
      'savings': 'Savings',
      'settings': 'Settings',
      'all_wallets': 'All Wallets',
      'total_balance': 'Total Balance',
      'income': 'Income',
      'expense': 'Expense',
      'transfer': 'Transfer',
      'this_month': 'This Month',
      'today': 'Today',
      '7_days': '7 Days',
      'all': 'All',
      'custom_range': 'Custom Date',
      'new_tx': 'New Transaction',
      'edit_tx': 'Edit Transaction',
      'amount': 'Amount',
      'category': 'Category',
      'wallet': 'Wallet',
      'from_wallet': 'From Wallet',
      'to_wallet': 'To Wallet',
      'note': 'Note',
      'date': 'Date',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'savings_goals': 'Savings Goals',
      'add_goal': 'Add New Goal',
      'goal_title': 'Goal Name (e.g. New Laptop, Emergency Fund)',
      'target_amount': 'Target Amount (\$)',
      'current_saved': 'Currently Saved (\$)',
      'deposit': 'Deposit Savings',
      'withdraw': 'Withdraw',
      'completed': 'Goal Completed!',
      'language': 'Language',
      'backup_restore': 'Data & Backup',
      'backup_drive': 'Backup to Drive / File',
      'restore_data': 'Restore Data (JSON)',
      'export_report': 'Export Report (PDF / Excel / CSV)',
      'app_lock': 'App Lock',
      'dark_mode': 'Dark Mode',
      'monthly_budget': 'Monthly Budget',
      'exchange_rate': 'Exchange Rate',
      'all_categories': 'All Categories',
      'stat_overview': 'Financial Analytics',
      'month_expense': 'Month Expense',
      'month_income': 'Month Income',
      'recent_7_days': 'Last 7 Days',
      'by_category': 'Spending by Category',
      'debt_tracker': 'Debt Tracker',
      'debts_and_loans': 'Debts & Loans Tracker',
      'to_receive': 'To Receive',
      'to_pay': 'To Pay',
      'monthly_trend': 'Monthly Spending Trend',
      'vs_last_month': 'vs Last Month',
      'repay': 'Record Repayment',
      'settled': 'Settled',
      'smart_insights': 'Smart Insights',
      'daily_avg': 'Daily Average',
      'peak_day': 'Peak Spending Day',
      'top_category': 'Top Category',
      'financial_tips': 'Financial Tips',
      'calendar_view': 'Calendar',
      'analytics_view': 'Analytics',
      'day_transactions': 'Day Transactions',
      'no_tx_day': 'No transactions on this day',
    },
  };
}
